### ISSUE TITLE
Has anyone get the result in paper on SHTechA?

### ISSUE THREAD

**Issue by CommissarMa** [CommissarMa/Context-Aware_Crowd_Counting-pytorch#1]
Paper get MAE=62.3 in ShTechA, but I only get 69.02. Are there any mistakes in my code?

**Comment by CommissarMa** [comment]
I get it.

**Comment by hellowangqian** [comment]
I downloaded your code and run it on ShTechA, can only get MAE=67 after 400 epochs. Is there any tip to get lower MAE? How many epochs are needed?
Thanks!

**Comment by RanRan-Margaret** [comment]
So how fix it?

**Comment by everRoc** [comment]
> I get it.

hi, can you share your methods to get lower MAE? I can only get MAE=68 after 350 epochs
