### ISSUE TITLE
How to see the person count?

### ISSUE THREAD

**Issue by mehedi-shafi** [CommissarMa/Context-Aware_Crowd_Counting-pytorch#10]
I am sorry if it comes out wrong. I have run the project successfully and tested on images from Shanghai dataset. I would like to see the number of person predicted. Is it possible?

**Comment by CommissarMa** [comment]
![image](https://user-images.githubusercontent.com/18243899/61788369-842c0f80-ae44-11e9-92b1-4cb9e6dc425b.png)

you can add the code in red to show the number of person predicted.

**Comment by mehedi-shafi** [comment]
Thanks it worked. Although the outcome is in decimal.

**Comment by zgzhengSEU** [comment]
Does using the density map with eight times downsampling have no effect on the total number of people?
