### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by aain3314** [CommissarMa/Context-Aware_Crowd_Counting-pytorch#15]
FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
在生成.npy的时候，生成不了

**Comment by aain3314** [comment]
![image](https://user-images.githubusercontent.com/53817955/62686195-cb92ce00-b9f6-11e9-9be6-e803c4ebfadd.png)

**Comment by lucyandjason** [comment]
How you solve this problem ,I make the same problem.
