### ISSUE TITLE
about result 

### ISSUE THREAD

**Issue by yanfangfangfang** [CommissarMa/Context-Aware_Crowd_Counting-pytorch#2]
thanks for your code. but when i run ,i cant got same result as you say mae=62.3,at epoch 353. 
![image](https://user-images.githubusercontent.com/47957488/58232563-666efb00-7d6c-11e9-9e80-98226c093af4.png)
can you give me some advice.
all code not change expect the path of data.

**Comment by CommissarMa** [comment]
I have run the code for about ten times. In my memory, the mae can be less than 100 at ~10th epoch. Just now I run the code again and get the following result:  
![image](https://user-images.githubusercontent.com/18243899/58234384-f9aa2f80-7d70-11e9-82ef-b14ff8394dd6.png)  
May be you can try again.  I can't find any other possibility for now.
Good luck!   
If you find the reason , please inform me, thank you.

**Comment by CommissarMa** [comment]
I have run the code for about ten times. In my memory, the mae can be less than 100 at ~10th epoch. Just now I run the code again and get the following result:
![image](https://user-images.githubusercontent.com/18243899/58235171-db453380-7d72-11e9-8e50-5d0e3a0d1b02.png)  
May be you can try again. I can't find any other possibility for now.
Good luck!
If you find the reason , please inform me, thank you.

**Comment by ElaineXiaoke** [comment]
> thanks for your code. but when i run ,i cant got same result as you say mae=62.3,at epoch 353.
> ![image](https://user-images.githubusercontent.com/47957488/58232563-666efb00-7d6c-11e9-9e80-98226c093af4.png)
> can you give me some advice.
> all code not change expect the path of data.

Did you solve the problem? I also tried the code but I could only get large MAE as you did. Would you mind sharing your solutions if you fix it?

**Comment by CommissarMa** [comment]
@yanfangfangfang @ElaineXiaoke  I think maybe the problem is at the generation of density map. You can check the data_preparation/k_nearest_gaussian_kernel.py to generate the correct density map. I think it will work.

**Comment by yanfangfangfang** [comment]
![image](https://user-images.githubusercontent.com/47957488/58614532-31722380-82eb-11e9-93ec-cc883a646020.png)
in  the code of data_preparation/k_nearest_gaussian_kernel.py.   'gt' don't definie before ,maybe there should be   'points'

**Comment by csonde** [comment]
Hey!

Just putting this here, it might be related.

Thanks for this, I am using it for a custom dataset, and seems to be working with some small issues. I can achieve nice results. I would like to point out 2 things though. First in the line below, an integer is divided by another one.

https://github.com/CommissarMa/Context-Aware_Crowd_Counting-pytorch/blob/07f86a5d03664b87812557c429df1835cb2e3124/my_dataset.py#L35

Now in Python 2.7 this will yield another integer, so in our case 0 or 1, but most likely 0. So if someone is using 2.7 then changing to 3.x could solve this, Or change 255 to 255.0 (I recommend the latter). I also got awful results before doing so.

The second thing is for the validation part. In the dataset enumerator you are doing a random flip if I am not mistaken.

https://github.com/CommissarMa/Context-Aware_Crowd_Counting-pytorch/blob/07f86a5d03664b87812557c429df1835cb2e3124/my_dataset.py#L43-L45

I assume this is for data augmentation. Which is nice and helps the training procedure, but not very fortunate during validation in my opinion. It is just a suggestion, it would be better to not flip any image, or flip all, or validate on both normal and flipped images, or basically any option is good, which does not involve randomness for validation. Although if one considers the possibility to compare results to other methods then most likely the "no flipping" version is the most desirable, to help to ensure that the results are evaluated on the same set.

**Comment by yanfangfangfang** [comment]
very thanks for your advices. and i run code with python 2.7  there should be  /255.0.

![image](https://user-images.githubusercontent.com/47957488/58631416-0a304c00-8315-11e9-8e6f-af6bb47f001f.png)

**Comment by CommissarMa** [comment]
@csonde You are right. I will fix them. Thank you.

**Comment by xinke-wang** [comment]
Hi @yanfangfangfang , have you finally achieved the MAE (62.3) which was proposed in the paper for Shanghai Part A ? As I can only get about 66 even after 1000 epochs. Many thanks.

**Comment by yanfangfangfang** [comment]
> Hi @yanfangfangfang , have you finally achieved the MAE (62.3) which was proposed in the paper for Shanghai Part A ? As I can only get about 66 even after 1000 epochs. Many thanks.

no i just got the same result as you, i can't found my problem. but i use the pre-model of code author can reach the MAE(about 62). if you fix, please concat ,thank you very much.

**Comment by xinke-wang** [comment]
> > Hi @yanfangfangfang , have you finally achieved the MAE (62.3) which was proposed in the paper for Shanghai Part A ? As I can only get about 66 even after 1000 epochs. Many thanks.
> 
> no i just got the same result as you, i can't found my problem. but i use the pre-model of code author can reach the MAE(about 62). if you fix, please concat ,thank you very much.

Thank you for your prompt reply, I will update it if I reach the MAE.

**Comment by RanRan-Margaret** [comment]
I have the same problem that mae=66,Have you fix it?

**Comment by RanRan-Margaret** [comment]
> > > Hi @yanfangfangfang , have you finally achieved the MAE (62.3) which was proposed in the paper for Shanghai Part A ? As I can only get about 66 even after 1000 epochs. Many thanks.
> > 
> > 
> > no i just got the same result as you, i can't found my problem. but i use the pre-model of code author can reach the MAE(about 62). if you fix, please concat ,thank you very much.
> 
> Thank you for your prompt reply, I will update it if I reach the MAE.

I have the same problem that mae=66,Have you fix it?
