### ISSUE TITLE
Get result from model output

### ISSUE THREAD

**Issue by marcusvlc** [CommissarMa/Context-Aware_Crowd_Counting-pytorch#21]
I am creating an algorithm that counts people in real time, and I am interested in using your repository, however, I have a question. When performing an inference with the command

`et_dmap = model (img)
`
the result of the amount of people in the image would be

`et_dmap.data.sum() ?
`
I was in doubt because I am using the .pth provided by you and I'm having a bit strange results.

**Comment by CommissarMa** [comment]
yes，just sum. You are right. However, when you directly use the trained model to your scene, due to the gap of different scenes, you may get terrible result. My advise is that you annotate several images of your scene and petform tranfer learning.&nbsp;



---Original---
