### ISSUE TITLE
Some problem of k_nearest_gaussian_kernel.py

### ISSUE THREAD

**Issue by GChen-ai** [CommissarMa/Context-Aware_Crowd_Counting-pytorch#23]
I found that if I use this method to generate the density maps, the count of the density map is different from the original .mat file. Is there something wrong? For example, the IMG_2 in ShanghaiTechA train data, the count of GT_IMG_2.mat is 707. But the count of the density map generated by your code is 698.
Thanks!

你好，我发现用你的代码生成的密度图和原始的.mat文件里的数目有些偏差，比如ShanghaiTech A里第二张图，原始的.mat文件中的label数是707，但用你的code生成的密度图sum之后是698。不知道是否有什么问题呢？还有你尝试过别的sigma和k取值的影响吗。
感谢!

**Comment by CommissarMa** [comment]
我觉得影响不大，你可以再把密度图放缩回原来mat中人数对应的密度。值得注意的是，有些头部在图像的边缘，存在部分的缺失，这样的头部也应该算1个人吗？
