### ISSUE TITLE
训练过程大概需要多久呢？SHTech_PartA

### ISSUE THREAD

**Issue by chw9413** [CommissarMa/Context-Aware_Crowd_Counting-pytorch#5]
第一次接触这类程序，请不要介意我的小白问题。.npy文件已成功生成，显卡是gtx1080，直接跑的代码里的数据集。在训练过程，每次读满两个进度条之后就出现[Errno 111] Connection refused的错误，然后又重新开始读两个进度条。不知道是我哪里的设置有问题，还是说本来这个训练的过程就需要一天以上的时间。
![1571834256](https://user-images.githubusercontent.com/46213358/58605578-dcbeb080-82ca-11e9-8d04-56228da2d92f.jpg)

**Comment by yanfangfangfang** [comment]
这个错误应该是 visdom 这个库的原因 我也有报错，我注释了这个部分就没有报错了。但是我也不知道怎么改，如果你知道了 麻烦告诉我一下 谢谢

**Comment by chw9413** [comment]
> 这个错误应该是 visdom 这个库的原因 我也有报错，我注释了这个部分就没有报错了。但是我也不知道怎么改，如果你知道了 麻烦告诉我一下 谢谢

那你注释掉那个库的话对结果有什么影响吗？还有就是你训练花了多久时间呢？

**Comment by CommissarMa** [comment]
@chw9413 @yanfangfangfang  我更新了readme，visdom是一个可视化库，类似tensorboard，使用前需要在命令行中输入python -m visdom.server，这样就可以在浏览器中看到输出的密度图了。

**Comment by CommissarMa** [comment]
@chw9413 @yanfangfangfang 训练时间取决于你训练多少个epoch，基本上一个epoch在1分钟左右。

**Comment by chw9413** [comment]
@CommissarMa 那我只修改了代码中的文件夹路径，将近一天的时间，checkpoints中epoch_*.pth已经存到208了。它默认epoch到多少会停止训练呢？

**Comment by chw9413** [comment]
@CommissarMa 噢噢，好的，谢谢大佬解答。默认的epoch得到20000是吧？一天过去了，我才到209…我还是改小一点吧…再把visdom加上

**Comment by aain3314** [comment]
> 第一次接触这类程序，请不要介意我的小白问题..npy文件已成功生成，显卡是gtx1080，直接跑的代码里的数据集。在训练过程，每次读满两个进度条之后就出现[Errno 111] Connection refused的错误，然后又重新开始读两个进度条。不知道是我哪里的设置有问题，还是说本来这个训练的过程就需要一天以上的时间。
> ![1571834256](https://user-images.githubusercontent.com/46213358/58605578-dcbeb080-82ca-11e9-8d04-56228da2d92f.jpg)

.npy怎么生成的啊，运行作者的代码没有啊

**Comment by chw9413** [comment]
@aain3314 就跑一下data_preparation里面的代码就可以了。要等一段时间就能看到npy文件了

**Comment by aain3314** [comment]
![image](https://user-images.githubusercontent.com/53817955/62685390-25929400-b9f5-11e9-9c72-ad0dcc676f52.png)
我这个地方有错误生成不了，请问怎么解决

**Comment by aain3314** [comment]
FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
